# Generated by Django 4.1.3 on 2022-12-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('Imdb', models.FloatField()),
            ],
        ),
    ]
